#!/usr/bin/env node
/*
 * Regenerate supabase/schema.sql from the migrations.
 *
 *   node scripts/build-schema.mjs
 *
 * schema.sql is every migration concatenated in filename order and nothing
 * else. It exists so a fresh project can be stood up by pasting one file into
 * the Supabase SQL editor, with no CLI and no link step.
 *
 * It is GENERATED, and that is the whole point: a hand-maintained "full schema"
 * drifts from the migrations the moment somebody edits one and forgets the
 * other, and the drift is invisible until a column the application selects by
 * name is not there. Change a migration, run this, commit both.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const MIGRATIONS = 'supabase/migrations'
const OUT = 'supabase/schema.sql'

const RULE = `-- ${'='.repeat(76)}`

const HEADER = `-- ${'='.repeat(77)}
-- Lead Engine — the whole schema, in one file.
--
-- WHAT THIS IS
--
-- Every migration in supabase/migrations/, concatenated in filename order and
-- nothing else. It is GENERATED by scripts/build-schema.mjs, so it cannot drift
-- from what the application expects — the migrations remain the source of
-- truth. Change a migration, re-run that script, commit both.
--
-- HOW TO RUN IT
--
--   Supabase dashboard -> SQL Editor -> New query -> paste this whole file ->
--   Run. It takes a few seconds.
--
-- It assumes an EMPTY database — a fresh Supabase project, nothing created in
-- \`public\` yet. Running it twice will fail on the first \`create table\`, which is
-- the intended behaviour: this file builds a schema, it does not reconcile one.
--
-- BEFORE YOU RUN IT: enable pg_cron.
--
--   Dashboard -> Database -> Extensions -> search "pg_cron" -> enable.
--
-- The file asks for it too (\`create extension if not exists pg_cron\`), and in
-- the SQL editor you are \`postgres\`, so that usually succeeds on its own. But if
-- it does not, four scheduled jobs silently never get created — and three of
-- them are the retention promises: Google-sourced search results, cached
-- geocodes and fetched reviews expiring on their own, whether or not the app is
-- deployed or awake. Part-way through, this file asserts the original three are
-- scheduled and re-schedules any that are missing, so a missing pg_cron surfaces
-- as an error there rather than as a year of data that quietly failed to expire.
--
-- AFTERWARDS, confirm the jobs exist:
--
--   select * from public.scheduled_jobs;
--
-- Four rows: expire-search-results (03:15 UTC), expire-geocode-cache (03:20),
-- expire-place-reviews (03:25) and purge-deleted-leads (03:45). The fifth
-- scheduled job — the nightly Google refresh — is a Vercel cron rather than a
-- database one, because it has to call Google and Postgres cannot. See
-- vercel.json and the README.
--
-- WHAT YOU GET
--
--   Transient side   searches, search_results,
--                    place_review_fetches, place_reviews
--   Permanent side   leads, lead_audits, lead_audit_findings, lead_scores,
--                    lead_notes, lead_activities, lead_refreshes,
--                    call_briefings, lists, lead_lists, saved_views
--   Cost control     api_usage, app_settings, geocode_cache
--   Read models      leads_library, lead_score_queue, lead_scoring_inputs,
--                    lead_facet_values, lead_status_counts, lead_list_counts,
--                    scheduled_jobs
--
-- A NOTE ON SECURITY, because it will look wrong in the advisor.
--
-- Every table has RLS enabled with NO policies, and USAGE on the \`public\` schema
-- is revoked from PUBLIC, \`anon\` and \`authenticated\`. That is deliberate and it
-- is the whole authorization model: sessions belong to NextAuth, so there is no
-- Supabase JWT and no auth.uid() for a policy to inspect. A leaked publishable
-- key fails at the schema, before it can name a table. \`service_role\` — what the
-- secret key resolves to — is granted explicitly and untouched.
--
-- Supabase's security advisor will report "RLS enabled, no policy" on every
-- table. Here that notice is the desired state, not a finding to fix.
-- ${'='.repeat(77)}


`

const names = (await readdir(MIGRATIONS)).filter((name) => name.endsWith('.sql')).sort()
if (!names.length) throw new Error(`No migrations found in ${MIGRATIONS}`)

const sections = await Promise.all(
  names.map(async (name) => {
    const body = await readFile(join(MIGRATIONS, name), 'utf8')
    return `${RULE}\n-- ${name}\n${RULE}\n\n${body.trimEnd()}\n\n\n`
  }),
)

const out = `${HEADER}${sections.join('')}`.trimEnd() + '\n'
await writeFile(OUT, out)

console.log(`${OUT} — ${names.length} migrations, ${out.length.toLocaleString('en-US')} bytes`)
